/**
 * Build script: bundles multi-theme templates/ into src/generated/ TypeScript modules.
 * Precompiles Handlebars templates so Workers (no eval) can render them.
 * Run with: tsx tools/build-assets.ts
 *
 * Directory structure:
 *   templates/<theme>/layouts/*.html
 *   templates/<theme>/partials/*.html
 *   templates/<theme>/*.html          (page templates)
 */
import fs from 'node:fs';
import path from 'node:path';
import Handlebars from 'handlebars';

const ROOT = path.resolve(import.meta.dirname, '..');
const TEMPLATES_DIR = path.join(ROOT, 'templates');
const PAGES_DIR = path.join(ROOT, 'pages');
const GENERATED_DIR = path.join(ROOT, 'src', 'generated');

// Ensure output directory
fs.mkdirSync(GENERATED_DIR, { recursive: true });

function escapeTemplateLiteral(str: string): string {
  return str.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${');
}

const toExportName = (name: string) => name.replace(/-/g, '_');

// ─── Discover themes ──────────────────────────────────────

function discoverThemes(): string[] {
  return fs.readdirSync(TEMPLATES_DIR).filter((entry) => {
    const full = path.join(TEMPLATES_DIR, entry);
    return fs.statSync(full).isDirectory() && !entry.startsWith('.');
  });
}

// ─── Load template sources for a single theme ─────────────

function loadThemeSources(theme: string): {
  layouts: Record<string, string>;
  partials: Record<string, string>;
  pages: Record<string, string>;
} {
  const themeDir = path.join(TEMPLATES_DIR, theme);
  const layouts: Record<string, string> = {};
  const partials: Record<string, string> = {};
  const pages: Record<string, string> = {};

  const layoutsDir = path.join(themeDir, 'layouts');
  if (fs.existsSync(layoutsDir)) {
    for (const file of fs.readdirSync(layoutsDir)) {
      if (!file.endsWith('.html')) continue;
      const name = path.basename(file, '.html');
      layouts[name] = fs.readFileSync(path.join(layoutsDir, file), 'utf-8');
    }
  }

  const partialsDir = path.join(themeDir, 'partials');
  if (fs.existsSync(partialsDir)) {
    for (const file of fs.readdirSync(partialsDir)) {
      if (!file.endsWith('.html')) continue;
      const name = path.basename(file, '.html');
      partials[name] = fs.readFileSync(path.join(partialsDir, file), 'utf-8');
    }
  }

  // Page templates are .html files directly in the theme directory
  for (const file of fs.readdirSync(themeDir)) {
    if (!file.endsWith('.html')) continue;
    const name = path.basename(file, '.html');
    pages[name] = fs.readFileSync(path.join(themeDir, file), 'utf-8');
  }

  return { layouts, partials, pages };
}

// ─── Emit precompiled templates (multi-theme) ─────────────

function emitPrecompiledTemplates(): void {
  const themes = discoverThemes();
  console.log(`[build] Discovered themes: ${themes.join(', ')}`);

  const out: string[] = [
    '// AUTO-GENERATED by tools/build-assets.ts — do not edit manually',
    '// Precompiled Handlebars templates for CF Workers (no runtime compile/eval)',
    '// @ts-nocheck',
    '',
    `export const THEMES = ${JSON.stringify(themes)};`,
    '',
  ];

  for (const theme of themes) {
    const { layouts, partials, pages } = loadThemeSources(theme);
    const themePrefix = toExportName(theme);

    for (const [name, content] of Object.entries(partials)) {
      const code = Handlebars.precompile(content, { strict: false });
      const exportName = `${themePrefix}__partial_${toExportName(name)}`;
      out.push(`export const ${exportName} = ${code};`);
      out.push('');
    }

    for (const [name, content] of Object.entries(layouts)) {
      const code = Handlebars.precompile(content, { strict: false });
      const exportName = `${themePrefix}__layout_${toExportName(name)}`;
      out.push(`export const ${exportName} = ${code};`);
      out.push('');
    }

    for (const [name, content] of Object.entries(pages)) {
      const code = Handlebars.precompile(content, { strict: false });
      const exportName = `${themePrefix}__page_${toExportName(name)}`;
      out.push(`export const ${exportName} = ${code};`);
      out.push('');
    }

    console.log(`[build]   ${theme}: ${Object.keys(layouts).length} layouts, ${Object.keys(partials).length} partials, ${Object.keys(pages).length} pages`);
  }

  fs.writeFileSync(path.join(GENERATED_DIR, 'templates-compiled.js'), out.join('\n'), 'utf-8');
  console.log('[build] Generated templates-compiled.js (precompiled for Workers)');
}

// ─── Bundle raw template sources (for dev / reference) ────

function bundleTemplates(): void {
  const themes = discoverThemes();

  const lines: string[] = [
    '// AUTO-GENERATED by tools/build-assets.ts — do not edit manually',
    '',
    `export const THEMES = ${JSON.stringify(themes)};`,
    '',
  ];

  for (const theme of themes) {
    const { layouts, partials, pages } = loadThemeSources(theme);

    lines.push(`// Theme: ${theme}`);
    lines.push(`export const ${toExportName(theme)}_layouts: Record<string, string> = {`);
    for (const [name, content] of Object.entries(layouts)) {
      lines.push(`  ${JSON.stringify(name)}: \`${escapeTemplateLiteral(content)}\`,`);
    }
    lines.push('};');
    lines.push('');

    lines.push(`export const ${toExportName(theme)}_partials: Record<string, string> = {`);
    for (const [name, content] of Object.entries(partials)) {
      lines.push(`  ${JSON.stringify(name)}: \`${escapeTemplateLiteral(content)}\`,`);
    }
    lines.push('};');
    lines.push('');

    lines.push(`export const ${toExportName(theme)}_pages: Record<string, string> = {`);
    for (const [name, content] of Object.entries(pages)) {
      lines.push(`  ${JSON.stringify(name)}: \`${escapeTemplateLiteral(content)}\`,`);
    }
    lines.push('};');
    lines.push('');
  }

  fs.writeFileSync(path.join(GENERATED_DIR, 'templates.ts'), lines.join('\n'), 'utf-8');
  console.log('[build] Generated templates.ts (raw sources)');
}

// ─── Bundle Pages ──────────────────────────────────────────

function bundlePages(): void {
  if (!fs.existsSync(PAGES_DIR)) {
    console.log('[build] No pages/ directory found, skipping pages bundle.');
    fs.writeFileSync(
      path.join(GENERATED_DIR, 'pages.ts'),
      '// AUTO-GENERATED — no pages found\nexport const pages: Record<string, { title: string; description: string; content: string }> = {};\n',
      'utf-8',
    );
    return;
  }

  const registryPath = path.join(PAGES_DIR, '_registry.json');
  if (!fs.existsSync(registryPath)) {
    console.log('[build] No pages/_registry.json found, skipping pages bundle.');
    fs.writeFileSync(
      path.join(GENERATED_DIR, 'pages.ts'),
      '// AUTO-GENERATED — no pages found\nexport const pages: Record<string, { title: string; description: string; content: string }> = {};\n',
      'utf-8',
    );
    return;
  }

  const registry: Record<string, { title: string; description: string }> = JSON.parse(
    fs.readFileSync(registryPath, 'utf-8'),
  );

  const lines: string[] = [
    '// AUTO-GENERATED by tools/build-assets.ts — do not edit manually',
    '',
    'export const pages: Record<string, { title: string; description: string; content: string }> = {',
  ];

  let count = 0;
  for (const [slug, meta] of Object.entries(registry)) {
    const htmlPath = path.join(PAGES_DIR, `${slug}.html`);
    if (!fs.existsSync(htmlPath)) {
      console.warn(`[build] Warning: pages/${slug}.html not found, skipping`);
      continue;
    }
    const content = fs.readFileSync(htmlPath, 'utf-8');
    lines.push(`  ${JSON.stringify(slug)}: {`);
    lines.push(`    title: ${JSON.stringify(meta.title)},`);
    lines.push(`    description: ${JSON.stringify(meta.description)},`);
    lines.push(`    content: \`${escapeTemplateLiteral(content)}\`,`);
    lines.push(`  },`);
    count++;
  }

  lines.push('};');
  lines.push('');

  fs.writeFileSync(path.join(GENERATED_DIR, 'pages.ts'), lines.join('\n'), 'utf-8');
  console.log(`[build] Generated pages.ts (${count} pages)`);
}

// ─── Run ───────────────────────────────────────────────────

bundleTemplates();
emitPrecompiledTemplates();
bundlePages();
console.log('[build] Done.');
